### ISSUE TITLE
Ayar extend işlemi services için sorunlu

### ISSUE THREAD

**Issue by omerucel** [pozitim/ci#3]
Aşağıdaki ayar dosyasında suite1 için tanımlı services ayarı suite2 ve suite3 için kullanılamıyor. Ancak suite2 ve suite3 ayarları suite1 ile genişletiliyor.

``` yaml
suite1:
  image: pozitim-ci/centos-php54
  environments:
    APPLICATION_ENV: pozitim-ci
  services:
    gearmand:
    mongo:
    redis:
    mysql:
      database: test
  commands:
    - php -v

suite2:
  extend: suite1
  image: pozitim-ci/centos-php55

suite3:
  extend: suite2
  image: pozitim-ci/centos-php56
```
